### ISSUE TITLE
Outdated version of SDK has a few bugs

### ISSUE THREAD

**Issue by elsalakk** [RGBKit/CUESDK.NET#1]
Hey, first of all I appreciate the time and effort you put into making C# peoples lives easier in this regard.

There are a few ugly bugs in the older version of the SDK it would seem:
https://github.com/CorsairOfficial/cue-sdk/issues/11

Any chance we can get an update?

**Comment by elsalakk** [comment]
Note, I was able to simply drop in 3.0.355, and worked without issue, but I know they have added a few new call backs since.

**Comment by AndrewBabbitt97** [comment]
I know its a bit late, but the latest version of the SDK is now available on NuGet. I have also added all new enum values and structs along with new calls.
