### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brianmartinil** [RGBKit/CUESDK.NET#3]
What are the ramification of distributing a modified version of this library, either as a compiled DLL or source?  I'm working on a plugin for a product that is stuck on .Net Framework 4.5 (I can't change this).  I've successfully backported CUESDK.NET to work with that framework version, but I would need to distribute it as a DLL at a minimum.

**Comment by AndrewBabbitt97** [comment]
Will probably change license over to MIT.

The code base itself should support 4.5, we just need too add net45 to the target frameworks list in the csproj and publish it to nuget. I can see about doing this sometime today.

**Comment by brianmartinil** [comment]
I took a whack at adding a 4.5 target here:  https://github.com/brianmartinil/CUESDK.NET/tree/multiframework

I had to change some of the marshalling code to use non-generic versions of the methods.   It seems to work, but I don't do a lot of .Net and I definitely don't do much with interop.

**Comment by AndrewBabbitt97** [comment]
You were almost there, you were instantiating the types when you only needed to use typeof(). You can see what I mean on how I pushed the code for future reference: https://github.com/RGBKit/CUESDK.NET/commit/553b96528b517f3d5ebb8cd1b1e54e1f0d4a8b8c

I have also published these code changes on nuget: https://www.nuget.org/packages/CUESDK.NET/3.0.361.2

**Comment by brianmartinil** [comment]
Awesome, thanks!
