### ISSUE TITLE
RAM modules do not work

### ISSUE THREAD

**Issue by sygys** [RGBKit/CUESDK.NET#4]
Hi There, i love this thing and it is working very well for my fan controller and keyboard. Just wanted to let you know that this isnt working for my corsair RAM modules. They do show up in home assistant but i cannot control them. im using the vengeance RGB pro. Also my keyboard is showing as a seprate device but can be controlled with the "all_icue" entity. It would be awsome to being able to change my corsair headset and corsair keyboard seperately.

**Comment by AndrewBabbitt97** [comment]
I don't design the home assistant module, this was from someone else in the community.

This SDK can fully control devices separately, it's up to whoever uses the SDK to implement said functionality. 

As for Corsair RAM, it's hit or miss depending on motherboard manufacturer. Don't currently have any Corsair ram to test with.
